In [1]:
from sklearn.preprocessing import normalize;from sklearn.preprocessing import MinMaxScaler;import sklearn;from sklearn.impute import SimpleImputer;import statsmodels;import statsmodels.api as sm;from statsmodels.tsa.api import VAR
import numpy as np;import matplotlib.ticker as mticker
import scipy as sc;from scipy import linalg;import matplotlib.pyplot as plt;import numpy as np
from numpy import genfromtxt;from scipy.stats import beta
from scipy.stats import norm;from scipy.stats import gamma
from scipy.stats import invgamma;import matplotlib.pyplot as plt
import seaborn as sns;import math;import pandas as pd;import scipy as sc;from sklearn.mixture import GaussianMixture;from sklearn.mixture import BayesianGaussianMixture;import time;
import numpy as np;from sklearn.mixture import GaussianMixture;from sklearn import mixture
m= np.matmul;resh = np.reshape;norm= np.random.standard_normal;inv  = np.linalg.inv ;det = np.linalg.det
import time;import statsmodels.api as sm;from statsmodels.tsa.api import VAR
arr = np.array;zeros = np.zeros
import matplotlib.ticker as mtick
import scipy.io as sio 

In [4]:
### Prints ####
print('Hello World')

Hello World


In [6]:
### Variables ####
a_0  = 5
a_1 = 10
a_2 = 15

b = a_0+a_1
### assignent operators ###
b +=10
print(b)
b *=20
print(b)
b -=20
print(b)

25
500
480


In [13]:
### Lists ####

#### Lists are used to store multiple items in a single variable ####
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
### Check out more about: 
### https://docs.python.org/3.5/tutorial/datastructures.html#more-on-lists



In [ ]:
# This doesnt make any sense!! ##
list1[1]-list1[2]

In [14]:
## But this does! ##
list2[1]-list2[2]

-2

In [9]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"


[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [16]:
stack = [3, 4, 5]
print('initial list:', stack)
stack.append(6)
print('new list:', stack)
stack.append(7)
print('new list:', stack)
print('popped list:', stack.pop())
print('resulting list:',stack)
print('popped list:', stack.pop())
print('popped list:', stack.pop())
print('resulting list:',stack)

initial list: [3, 4, 5]
new list: [3, 4, 5, 6]
new list: [3, 4, 5, 6, 7]
popped list: 7
resulting list: [3, 4, 5, 6]
popped list: 6
popped list: 5
resulting list: [3, 4]


In [19]:
## For loop v Enumeration ##
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    #print('#%d: %s' % (idx + 1, animal))
    print(idx,animal)

    

0 cat
1 dog
2 monkey


In [ ]:
## Booleans : True v False 

In [45]:
a_0 = 9
a_1 = 10
print('Check if statement is true or not:', a_0>a_1)
print('Check if statement is true or not:', a_0<a_1)
## Can Assign condition as a variable: ##
b_0 = a_0>a_1
## can convert this into number: ##
print('resulting number:',int(b_0))
b_0 = a_0<a_1
print('resulting number:',int(b_0))
### What's the point of doing this? ###
k_0  = list([10,11,12])
k_1 = list()
k_1.append(int(kk[0]>=11))
k_1.append(int(kk[1]>=11))
k_1.append(int(kk[2]>=11))
### How many elements in the list are greater than or equal to 11: ##
print('Answer:',sum(k_1))

Check if statement is true or not: False
Check if statement is true or not: True
resulting number: 0
resulting number: 1
Answer: 2


In [48]:
## While  loop v For Loop:    ##
# Need to initialize variable to iterate over:
t =0
while t<10:
    print(t+1)
    t+=1

# No Need to initialize or increment while in the loop
for t in range(10):
    print(t)

    
## What's the difference? ###    
## Not much for simple operations

## Difference comes when there a condition that must be met!!!

## Example:
a = 0
condition = 0 
while condition==False:
    condition = a<100
    a+=10
    print(a,condition)

1
2
3
4
5
6
7
8
9
10
0
1
2
3
4
5
6
7
8
9
10 True


In [59]:
#### Arrays ###
### Need to use the package numpy ###
## This is the Bread and Butter of Python Development and Statistics !!!! #####

### Arrays are units that store numerical data in a fast/efficient manner ###
## Arrays can be used for many mathetical and statistical procedures ###
### Almost all of Deep learning / AI models use arrays to perform prediction/analysis
import numpy as np
a_0 = np.array([2,2,2])
a_1 = np.array([2,2,2])
a_3 = a_0+a_1
print(a_3.shape)
a_3 = np.reshape(a_3,[3,1])
print('Matrix Result:', a_3)
## Generate Normal distributed variables: ##
## Generate 3X3 Matrix:
A = np.random.standard_normal([3,3])
## Perform Matrix Multiplication: ##
c = np.matmul(A,a_3)
print('c shape:', c.shape)
### Assignment Operators: ###
print('c before:',c)
c+=3
print('c after:',c)
c*=3
print('c after:',c)

(3,)
Matrix Result: [[4]
 [4]
 [4]]
c shape: (3, 1)


In [70]:
### I can make 3D Arrays and perform 3D multiplication ###
# Dimension length
J = 2
N= 3
M = 3
C = np.random.standard_normal([J,M,N])
### I've produced 2 3X3 Matrices ###
print('Matrix 1:')
print(C[0])
print(' ')
print('Matrix 2:')
print(C[1])
 
# I can perform simulatenous computations of matrix inverse:
C_inv = np.linalg.inv(C)
# Check if the operation is correct:
err_0 = np.linalg.inv(C)[0]-np.linalg.inv(C[0])
err_1 = np.linalg.inv(C)[1]-np.linalg.inv(C[1])
print(' ')
## err_0 prints the resulting difference between 1rst matrix of C 's inverse and first matrix of C_inv
print('err_0:',np.sum(err_0) )
## err_1 prints the resulting difference between 2nd matrix of C 's inverse and second matrix of C_inv
print('err_1:',np.sum(err_1) )

Matrix 1:
[[-0.2313329   1.13367677 -0.18775662]
 [ 0.38518221  1.7419898   0.69464912]
 [-0.72403684  1.7101372  -0.18910731]]
 
Matrix 2:
[[ 1.77331366  1.112122   -0.65726658]
 [-0.98448253 -0.2559453   0.73644456]
 [-0.46647184 -1.15882208  2.68374258]]
 
err_0: 0.0
err_1: 0.0


In [72]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
# v.dot(w)
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
# x.dot(v)
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
# x.dot(y)
print(np.dot(x, y))



219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [81]:
### Elementwise multiplication of Matrices ##
A = np.random.standard_normal([2,2])
B = np.random.standard_normal([2,2])
print('Matrix A:')
print(' ')
print(A)
print(' ')
print('Matrix B:')
print(' ')
print(B)
print(' ')
print('Resultant Matrix:')
print(' ')
print(A*B)


Matrix A:
 
[[-2.06433744 -0.02996966]
 [-0.47728971 -0.65829196]]
 
Matrix B:
 
[[-0.59483927  0.17283501]
 [ 0.7895044   1.03448056]]
 
Resultant Matrix:
 
[[ 1.22794896 -0.00517981]
 [-0.37682232 -0.68099024]]


In [82]:
#### Methods (functions) in Python: ###

### Fuction allows you to avoid writing code repeatedly ###
def dothis(x,y):
    # x,y are inputs
    c = np.matmul(x,y)
    c+=c
    # Return function spits out the result of whatever you are trying to do
    return c


